CREATE TABLE IF NOT EXISTS submissions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL,
  email TEXT NOT NULL,
  name TEXT DEFAULT '',
  message TEXT DEFAULT '',
  created_at TEXT NOT NULL
);
